site_name: Learning Javascript
repo_url: https://pranabdas.github.io/
site_description: Learning Javascript
site_author: Pranab Das

nav:
    - Table of Contents: index.md
    - The Basics:
          - Setup: basics/setup.md
          - Console and external script: basics/console.md
          - Working with data: basics/working-with-data.md
          - Conditional statement: basics/conditional-statement.md
          - Arrays: basics/arrays.md
    - Functions and Objects:
          - Functions: functions-objects/functions.md
          - Variable scope: functions-objects/variable-scope.md
          - Objects: functions-objects/objects.md
          - map(): functions-objects/map.md
    - Loop:
          - loop: loop/loop.md
    - DOM:
          - Document Object Model: DOM/dom.md
          - Event handler: DOM/event-handler.md
    - Node.js:
          - Introduction: node/introduction.md
          - Standard input-output: node/std-input-output.md
          - Core modules: node/core-modules.md
          - File system: node/file-system.md
          - Understanding callbacks: node/callbacks.md
          - module.exports: node/module.exports.md
    - Electron.js:
          - Creating first Electron.js application: electron/electron.md
    - React.js:
          - React.js: react/react.md
          - To do list project: react/to-do-list.md
          - Shopping cart project: react/shopping-cart.md
          - Deploy to Github pages: react/githubpages.md
    - Misc:
          - Uninstall node (macOS): misc/node-uninstall.md
          - Updating npm packages: misc/npm-update.md

theme:
    name: null
    custom_dir: simplicity
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true
    hljs_languages: [javascript]

markdown_extensions:
    - pymdownx.arithmatex
    - attr_list

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
